### PR TITLE
add artifacts to actions 

### LINKED ISSUE #1032: Add artifacts to actions.
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [X] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [ ] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [X] Other subject matter not listed

---

### Description of your issue

*Explanation of your issue in arbitrary form goes here.*
Currently the github actions only provides a check for if the project builds after a pr, what I suggest is for it to also generate downloadable "artifacts", so we can submit issues with the latest development version of lightspark (building software on windows is pain).

### PR DESCRIPTION
**Pull request by Fancy2209**
Made by me with a lot of help from @huwdp 
Fixes #1032

### CODE REVIEW

**Comment by Fancy2209** [comment]
Fixed it not using secrets for the key. that was my bad.

**Comment by dbluelle** [comment]
Hmm, I'm getting an error in the "Add MXE repository to apt" step on windows builds:
```
Warning: Input 'keys' has been deprecated with message: deprecatged in favor of "keys-asc" input
Warning: Input 'key-server' has been deprecated with message: deprecatged in favor of "keys-asc" input
Run myci-actions/add-deb-repo@10
  with:
    repo: deb http://pkg.mxe.cc/repos/apt bionic main
    repo-name: mxe
    key-server: keyserver.ubuntu.com
    update: true
  env:
    CFLAGS: -std=c11
    CXXFLAGS: -std=c++11
Run if [ ! -z "keyserver.ubuntu.com" ] || [ ! -z "" ]; then
  if [ ! -z "keyserver.ubuntu.com" ] || [ ! -z "" ]; then
      if [ "$(id --user)" -eq "0" ]; then
          sudocmd=""
      else
          sudocmd="sudo"
      fi
  
      $sudocmd apt --quiet update --assume-yes || true
      $sudocmd apt --quiet install --assume-yes dirmngr curl apt-transport-https
  
      if [ ! -z "" ]; then
          echo "download ascii armored keys"
          curl --silent --show-error  | $sudocmd dd of=/etc/apt/trusted.gpg.d/mxe.asc
      elif [ ! -z "" ]; then
          echo "download key from keyserver"
          $sudocmd apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 
      else
          # try downloding key as if key-server is a direct URL to the key
          echo "download key from direct URL provided as key-server"
          curl --silent --show-error keyserver.ubuntu.com | $sudocmd apt-key add
      fi
  
      # update yarn key just in case, as it tends to expire often
      echo "update yarn key"
      curl --silent --show-error https://dl.yarnpkg.com/debian/pubkey.gpg | $sudocmd dd of=/etc/apt/trusted.gpg.d/yarn.asc
  else
      echo "no keys specified, nothing to import"
  fi
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    CFLAGS: -std=c11
    CXXFLAGS: -std=c++11

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [4003 B]
Hit:6 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Get:7 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2875 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [525 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [1113 kB]
Hit:10 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease
Get:11 http://azure.archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [154 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1868 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2540 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu bionic-security/main Translation-en [439 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [1082 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu bionic-security/restricted Translation-en [150 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1256 kB]
Get:18 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [315 kB]
Fetched 12.6 MB in 3s (4962 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
13 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.58.0-2ubuntu3.22).
dirmngr is already the newest version (2.2.4-1ubuntu1.6).
apt-transport-https is already the newest version (1.6.14).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
download key from direct URL provided as key-server
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
Error: Process completed with exit code 2.```

**Comment by huwdp** [comment]
I can't figure out what is going on. The key was added to the repo [here](https://github.com/Fancy2209/lightspark) and it [built properly](https://github.com/Fancy2209/lightspark/actions/runs/3981369035). I was thinking we could merge this and if it didn't work, we could revert back. I can't see anything wrong with the new build file.

**Comment by Fancy2209** [comment]
Neither can I
It built fine on my repo.

**Comment by Fancy2209** [comment]
Wait i found a issue.
Seems that the secret in the repo is broken!
It should only be the key. Not a url.

**Comment by Fancy2209** [comment]
Close inspection seems like the secret broke?
The log shows a blank space.
Can we use the key directly since it isn't secret anyways?

**Comment by dbluelle** [comment]
OK, merging the PR worked and the artifacts are created.
But they seem to be only downloadable by me and only when I'm logged in?!?
(see https://github.com/lightspark/lightspark/actions/runs/3988641412#artifacts)
Also there isn't created a release draft automatically ...
Do I have to create a release manually or are these files publically downloadable somewhere?

**Comment by huwdp** [comment]
Github Assets is an area where you just store things. I would have thought this would allow users to download the latest changes.

I think this can be easily changed so that it outputs a release instead.

**Comment by Fancy2209** [comment]
> OK, merging the PR worked and the artifacts are created. But they seem to be only downloadable by me and only when I'm logged in?!? (see https://github.com/lightspark/lightspark/actions/runs/3988641412#artifacts) Also there isn't created a release draft automatically ... Do I have to create a release manually or are these files publically downloadable somewhere?

I will see if I can get the release working.

**Pull request merged**
