### PR TITLE
Clean up Travis CI

### PR DESCRIPTION
**Pull request by jhwgh1968**
Cleanup of the Travis CI job.

Contains a change created by @tonytheodore as part of mxe/mxe#2349.

EDIT: Decided to get everything working at once compared to master.

### CODE REVIEW

**Comment by jhwgh1968** [comment]
The Travis build failed, but it worked on my master before I rebased. There were two commits in between mine and yours, @dbluelle, did they break something?

**Comment by tonytheodore** [comment]
[Removing `mxe-x86-64-w64-mingw32.static-gtk2`](https://github.com/lightspark/lightspark/commit/376e9da2e47012f2e5269ff65837486d93546eb9#diff-354f30a63fb0907d4ad57269548329e3L47) also removes jpeg (and possibly other transitive deps). Try adding `mxe-x86-64-w64-mingw32.static-jpeg`.

**Comment by tonytheodore** [comment]
See https://github.com/tonytheodore/lightspark/commit/a89046c976409f7e4672fc4b06f811ff178a3acc. native curl doesn't seem to be used, cmake is bundled with mxe and required by boost, and native nasm is required by ffmpeg via x264.

**Comment by jhwgh1968** [comment]
Once again, I'm very confused. It fails on this project's Travis with apt get problems:
https://travis-ci.com/lightspark/lightspark/jobs/208288645

But passes on mine when I just updated the PR:
https://travis-ci.org/jhwgh1968/lightspark/builds/545995164

**Comment by dbluelle** [comment]
I'm also very confused...
The build for both ubuntu and windows seems to be successful.
However travis says the builds where finished 25 minutes ago, but when looking at the details of the builds, the running indicator is still spinning and it says "running for 40 minutes".
The log has "Done. Your build exited with 0." as last entry.
Very weird.

**Pull request merged**
